// /api/status (GET only; other methods get 405 from Pages)
//   -> { checked_at, up, total, nodes: [{ slug, name, status: "up"|"slow"|"down", ms, url }] }
//   url is the public project URL (the widget links to it); `up` counts nodes that answered (up + slow).
// The node list is generated by tools/build_projects.py from tools/projects.json.
// Logic, timeouts and caching live in ../_lib/status-core.js. No request input is used.
import NODES from "../_lib/projects-live.json";
import { statusResponse } from "../_lib/status-core.js";

export function onRequestGet(context) {
  return statusResponse(context, NODES);
}
