// Renders a screenshot of the Spectro extension's visualizer window (read-only
// from ../../Spectro). chrome.* and tab capture are stubbed: the "tab audio" is a
// synthetic chord + noise generated by Web Audio, so the analyser has real input.
const path = require("path");
const { launch } = require("./pw");

const SRC = path.resolve(__dirname, "..", "..", "Spectro", "visualizer.html");
const OUT = process.argv[2] || path.resolve(__dirname, "..", "verify", "spectro-raw.png");
const MODE = Number(process.argv[3] || 1);
const THEME = Number(process.argv[4] || 0);

(async () => {
  const browser = await launch(["--autoplay-policy=no-user-gesture-required"]);
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 1 });
  await page.addInitScript(({ mode, theme }) => {
    window.chrome = { storage: { local: {
      get: (k, cb) => cb({ spectro: { mode, theme } }), set: () => {} } } };
    // Headless has no audio device, so feed the analyser a synthetic,
    // music-shaped spectrum (bass-heavy, a few harmonic peaks, time-varying).
    AnalyserNode.prototype.getByteFrequencyData = function (arr) {
      const t = performance.now() / 1000, n = arr.length;
      for (let i = 0; i < n; i++) {
        const x = i / n;
        let v = 235 * Math.exp(-x * 3.2) + 40 * Math.sin(i * 0.21 + t * 3) + 30 * Math.sin(i * 0.05 - t * 1.7);
        [0.03, 0.07, 0.12, 0.2, 0.31].forEach((p, k) => { v += (70 - k * 10) * Math.exp(-Math.pow((x - p) / 0.012, 2)); });
        if (x > 0.72) v *= Math.max(0, 1 - (x - 0.72) * 3);
        arr[i] = Math.max(0, Math.min(255, v));
      }
    };
    AnalyserNode.prototype.getByteTimeDomainData = function (arr) {
      const t = performance.now() / 1000, n = arr.length;
      for (let i = 0; i < n; i++) {
        const p = i / n * Math.PI * 2;
        arr[i] = 128 + 60 * Math.sin(p * 3 + t * 4) + 25 * Math.sin(p * 11 - t * 7) + 10 * Math.sin(p * 29);
      }
    };
    navigator.mediaDevices.getUserMedia = async () => {
      const ctx = new AudioContext();
      const dest = ctx.createMediaStreamDestination();
      const master = ctx.createGain(); master.gain.value = 0.5; master.connect(dest);
      [55, 110, 165, 220, 330, 440, 660, 880, 1320, 1760, 2640, 3520].forEach((f, i) => {
        const o = ctx.createOscillator(); o.type = i % 3 ? "sawtooth" : "square";
        o.frequency.value = f; const g = ctx.createGain(); g.gain.value = 0.35 / (1 + i * 0.6);
        o.connect(g); g.connect(master); o.start();
      });
      const buf = ctx.createBuffer(1, ctx.sampleRate * 2, ctx.sampleRate);
      const d = buf.getChannelData(0); for (let i = 0; i < d.length; i++) d[i] = (Math.random() * 2 - 1) * 0.15;
      const n = ctx.createBufferSource(); n.buffer = buf; n.loop = true; n.connect(master); n.start();
      return dest.stream;
    };
  }, { mode: MODE, theme: THEME });
  await page.goto("file:///" + SRC.replace(/\\/g, "/") + "?id=demo");
  await page.waitForTimeout(2500);
  await page.screenshot({ path: OUT });
  console.log("status:", await page.textContent("#status"), "->", OUT);
  await browser.close();
})();
